# Generated by Django 5.0.4 on 2024-05-02 08:52

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
