# Generated by Django 5.0.4 on 2024-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_file_path_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
    ]
